### ISSUE TITLE
Breadcrumb styles

### ISSUE THREAD

**Issue by knice** [knice/inquiry.ucsc.edu#11]
Breadcrumb links standout a little too much given that they are not primary content. They should be visible but not _dominant_ in the visual design. 

- I recommend changing the double caret to a single caret.
- Bring them a bit closer to the title of the article.
- Change them to a slightly lighter color.

**Comment by Herm71** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Slack/Github/Trello integration and workflow](https://trello.com/c/dvWOxcDZ/643-slack-github-trello-integration-and-workflow)
