### ISSUE TITLE
Add a class to  and style related links div block

### ISSUE THREAD

**Issue by knice** [knice/inquiry.ucsc.edu#12]
![screen-2017-07-19-90730](https://user-images.githubusercontent.com/36719/28377621-3c4fe6a8-6c62-11e7-9222-a2560c68c0a2.png)

1. The `div` block for related links does not have a class. Add `related-links` to the class attribute of the div block. 
2. I think the related links div block should be visually separated a bit more from the bottom of the article. Perhaps more top-margin and a light-colored border would accomplish this?

**Comment by Herm71** [comment]
Will do!
